### ISSUE TITLE
HourglassNet Checkpoint

### ISSUE THREAD

**Issue by amanrajdce** [princeton-vl/YouTube3D#3]
Hi, Will it be possible to provide hourglassnet model python file along with model checkpoint for which you reported the analysis in the first column and Table 3. in the paper here
https://arxiv.org/pdf/1806.09573.pdf

 I want to use the checkpoint model to initialize hourglass model and finetune it for another task that involves depth estimation in different settings. 

Thanks
Aman Raj

**Comment by wfchen-umich** [comment]
Hi Aman, I have updated code and uploaded the pretrained model.

**Comment by amanrajdce** [comment]
thank you so much @wfchen-umich  for quick response on this and sharing the model.
