### ISSUE TITLE
Hourglass - NYU + DIW model?

### ISSUE THREAD

**Issue by JamieWatson683** [princeton-vl/YouTube3D#4]
First - great work on the paper!

I was wondering if you still had the baseline hourglass model you compare to in Table3 of the paper, first row - Hourglass network pretrained using DIW and NYU? I know I could be asking on the original DIW repo, but a pytorch version would be ideal if at all possible.

I'm planning to use it as a baseline for an upcoming piece of work.
Thanks a lot

**Comment by wfchen-umich** [comment]
Hi,
Thanks for your interest in our paper. 
Yes that baseline can be found in: https://drive.google.com/drive/folders/1Eyc8k1PbQcGBG7AU54DlD4uhSo2WOeqw?usp=sharing
Let me know if you encounter any problems.

**Comment by JamieWatson683** [comment]
Oh perfect, thanks a lot for getting back so quickly - got it running now, looks good!
