### ISSUE TITLE
Pytorch Version

### ISSUE THREAD

**Issue by uday701** [princeton-vl/YouTube3D#5]
Can you please let me know whether we can compile the code with Pytorch version>=1.0 ?

Because to compile with Pytorch 0.2 it requires Cuda7.5 and Cuda7.5 is only compatible upto ubuntu 14.04 version.

**Comment by wfchen-umich** [comment]
Hi,
I think you can easily make a little change to the code to make it work with Pytorch version >=1.0. For reference, you can take a look at https://github.com/princeton-vl/oasis/tree/master/experiments/depth.

**Comment by uday701** [comment]
Ok, Thanks.
